/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AccountsPayable } from "./AccountsPayable";
import { AccountsPayableCountArgs } from "./AccountsPayableCountArgs";
import { AccountsPayableFindManyArgs } from "./AccountsPayableFindManyArgs";
import { AccountsPayableFindUniqueArgs } from "./AccountsPayableFindUniqueArgs";
import { CreateAccountsPayableArgs } from "./CreateAccountsPayableArgs";
import { UpdateAccountsPayableArgs } from "./UpdateAccountsPayableArgs";
import { DeleteAccountsPayableArgs } from "./DeleteAccountsPayableArgs";
import { AccountsPayableService } from "../accountsPayable.service";
@graphql.Resolver(() => AccountsPayable)
export class AccountsPayableResolverBase {
  constructor(protected readonly service: AccountsPayableService) {}

  async _accountsPayablesMeta(
    @graphql.Args() args: AccountsPayableCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AccountsPayable])
  async accountsPayables(
    @graphql.Args() args: AccountsPayableFindManyArgs
  ): Promise<AccountsPayable[]> {
    return this.service.accountsPayables(args);
  }

  @graphql.Query(() => AccountsPayable, { nullable: true })
  async accountsPayable(
    @graphql.Args() args: AccountsPayableFindUniqueArgs
  ): Promise<AccountsPayable | null> {
    const result = await this.service.accountsPayable(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AccountsPayable)
  async createAccountsPayable(
    @graphql.Args() args: CreateAccountsPayableArgs
  ): Promise<AccountsPayable> {
    return await this.service.createAccountsPayable({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => AccountsPayable)
  async updateAccountsPayable(
    @graphql.Args() args: UpdateAccountsPayableArgs
  ): Promise<AccountsPayable | null> {
    try {
      return await this.service.updateAccountsPayable({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AccountsPayable)
  async deleteAccountsPayable(
    @graphql.Args() args: DeleteAccountsPayableArgs
  ): Promise<AccountsPayable | null> {
    try {
      return await this.service.deleteAccountsPayable(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
