/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AccountsReceivableService } from "../accountsReceivable.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccountsReceivableCreateInput } from "./AccountsReceivableCreateInput";
import { AccountsReceivable } from "./AccountsReceivable";
import { AccountsReceivableFindManyArgs } from "./AccountsReceivableFindManyArgs";
import { AccountsReceivableWhereUniqueInput } from "./AccountsReceivableWhereUniqueInput";
import { AccountsReceivableUpdateInput } from "./AccountsReceivableUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AccountsReceivableControllerBase {
  constructor(
    protected readonly service: AccountsReceivableService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccountsReceivable })
  @nestAccessControl.UseRoles({
    resource: "AccountsReceivable",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AccountsReceivableCreateInput,
  })
  async createAccountsReceivable(
    @common.Body() data: AccountsReceivableCreateInput
  ): Promise<AccountsReceivable> {
    return await this.service.createAccountsReceivable({
      data: data,
      select: {
        amount: true,
        createdAt: true,
        customerId: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AccountsReceivable] })
  @ApiNestedQuery(AccountsReceivableFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AccountsReceivable",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accountsReceivables(
    @common.Req() request: Request
  ): Promise<AccountsReceivable[]> {
    const args = plainToClass(AccountsReceivableFindManyArgs, request.query);
    return this.service.accountsReceivables({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        customerId: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccountsReceivable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccountsReceivable",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accountsReceivable(
    @common.Param() params: AccountsReceivableWhereUniqueInput
  ): Promise<AccountsReceivable | null> {
    const result = await this.service.accountsReceivable({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        customerId: true,
        dueDate: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccountsReceivable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccountsReceivable",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: AccountsReceivableUpdateInput,
  })
  async updateAccountsReceivable(
    @common.Param() params: AccountsReceivableWhereUniqueInput,
    @common.Body() data: AccountsReceivableUpdateInput
  ): Promise<AccountsReceivable | null> {
    try {
      return await this.service.updateAccountsReceivable({
        where: params,
        data: data,
        select: {
          amount: true,
          createdAt: true,
          customerId: true,
          dueDate: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccountsReceivable })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccountsReceivable",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAccountsReceivable(
    @common.Param() params: AccountsReceivableWhereUniqueInput
  ): Promise<AccountsReceivable | null> {
    try {
      return await this.service.deleteAccountsReceivable({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          customerId: true,
          dueDate: true,
          id: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
