/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Attendance } from "../../attendance/base/Attendance";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { Benefit } from "../../benefit/base/Benefit";
import { Leave } from "../../leave/base/Leave";
import { Payroll } from "../../payroll/base/Payroll";
import { Performance } from "../../performance/base/Performance";
import { SelfService } from "../../selfService/base/SelfService";
import { Talent } from "../../talent/base/Talent";
import { Workforce } from "../../workforce/base/Workforce";

@ObjectType()
class Employee {
  @ApiProperty({
    required: false,
    type: () => [Attendance],
  })
  @ValidateNested()
  @Type(() => Attendance)
  @IsOptional()
  attendances?: Array<Attendance>;

  @ApiProperty({
    required: false,
    type: () => [Benefit],
  })
  @ValidateNested()
  @Type(() => Benefit)
  @IsOptional()
  benefits?: Array<Benefit>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth!: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  hireDate!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Leave],
  })
  @ValidateNested()
  @Type(() => Leave)
  @IsOptional()
  leaves?: Array<Leave>;

  @ApiProperty({
    required: false,
    type: () => [Payroll],
  })
  @ValidateNested()
  @Type(() => Payroll)
  @IsOptional()
  payrolls?: Array<Payroll>;

  @ApiProperty({
    required: false,
    type: () => [Performance],
  })
  @ValidateNested()
  @Type(() => Performance)
  @IsOptional()
  performances?: Array<Performance>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone!: string | null;

  @ApiProperty({
    required: false,
    type: () => [SelfService],
  })
  @ValidateNested()
  @Type(() => SelfService)
  @IsOptional()
  selfServices?: Array<SelfService>;

  @ApiProperty({
    required: false,
    type: () => [Talent],
  })
  @ValidateNested()
  @Type(() => Talent)
  @IsOptional()
  talents?: Array<Talent>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Workforce],
  })
  @ValidateNested()
  @Type(() => Workforce)
  @IsOptional()
  workforces?: Array<Workforce>;
}

export { Employee as Employee };
