/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FinancialReportService } from "../financialReport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FinancialReportCreateInput } from "./FinancialReportCreateInput";
import { FinancialReport } from "./FinancialReport";
import { FinancialReportFindManyArgs } from "./FinancialReportFindManyArgs";
import { FinancialReportWhereUniqueInput } from "./FinancialReportWhereUniqueInput";
import { FinancialReportUpdateInput } from "./FinancialReportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FinancialReportControllerBase {
  constructor(
    protected readonly service: FinancialReportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FinancialReport })
  @nestAccessControl.UseRoles({
    resource: "FinancialReport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: FinancialReportCreateInput,
  })
  async createFinancialReport(
    @common.Body() data: FinancialReportCreateInput
  ): Promise<FinancialReport> {
    return await this.service.createFinancialReport({
      data: data,
      select: {
        createdAt: true,
        details: true,
        id: true,
        period: true,
        reportName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FinancialReport] })
  @ApiNestedQuery(FinancialReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FinancialReport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialReports(
    @common.Req() request: Request
  ): Promise<FinancialReport[]> {
    const args = plainToClass(FinancialReportFindManyArgs, request.query);
    return this.service.financialReports({
      ...args,
      select: {
        createdAt: true,
        details: true,
        id: true,
        period: true,
        reportName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FinancialReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialReport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async financialReport(
    @common.Param() params: FinancialReportWhereUniqueInput
  ): Promise<FinancialReport | null> {
    const result = await this.service.financialReport({
      where: params,
      select: {
        createdAt: true,
        details: true,
        id: true,
        period: true,
        reportName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FinancialReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialReport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: FinancialReportUpdateInput,
  })
  async updateFinancialReport(
    @common.Param() params: FinancialReportWhereUniqueInput,
    @common.Body() data: FinancialReportUpdateInput
  ): Promise<FinancialReport | null> {
    try {
      return await this.service.updateFinancialReport({
        where: params,
        data: data,
        select: {
          createdAt: true,
          details: true,
          id: true,
          period: true,
          reportName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FinancialReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FinancialReport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFinancialReport(
    @common.Param() params: FinancialReportWhereUniqueInput
  ): Promise<FinancialReport | null> {
    try {
      return await this.service.deleteFinancialReport({
        where: params,
        select: {
          createdAt: true,
          details: true,
          id: true,
          period: true,
          reportName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
