/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Talent } from "./Talent";
import { TalentCountArgs } from "./TalentCountArgs";
import { TalentFindManyArgs } from "./TalentFindManyArgs";
import { TalentFindUniqueArgs } from "./TalentFindUniqueArgs";
import { CreateTalentArgs } from "./CreateTalentArgs";
import { UpdateTalentArgs } from "./UpdateTalentArgs";
import { DeleteTalentArgs } from "./DeleteTalentArgs";
import { Employee } from "../../employee/base/Employee";
import { TalentService } from "../talent.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Talent)
export class TalentResolverBase {
  constructor(
    protected readonly service: TalentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "read",
    possession: "any",
  })
  async _talentsMeta(
    @graphql.Args() args: TalentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Talent])
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "read",
    possession: "any",
  })
  async talents(@graphql.Args() args: TalentFindManyArgs): Promise<Talent[]> {
    return this.service.talents(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Talent, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "read",
    possession: "own",
  })
  async talent(
    @graphql.Args() args: TalentFindUniqueArgs
  ): Promise<Talent | null> {
    const result = await this.service.talent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Talent)
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "create",
    possession: "any",
  })
  async createTalent(@graphql.Args() args: CreateTalentArgs): Promise<Talent> {
    return await this.service.createTalent({
      ...args,
      data: {
        ...args.data,

        employee: args.data.employee
          ? {
              connect: args.data.employee,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Talent)
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "update",
    possession: "any",
  })
  async updateTalent(
    @graphql.Args() args: UpdateTalentArgs
  ): Promise<Talent | null> {
    try {
      return await this.service.updateTalent({
        ...args,
        data: {
          ...args.data,

          employee: args.data.employee
            ? {
                connect: args.data.employee,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Talent)
  @nestAccessControl.UseRoles({
    resource: "Talent",
    action: "delete",
    possession: "any",
  })
  async deleteTalent(
    @graphql.Args() args: DeleteTalentArgs
  ): Promise<Talent | null> {
    try {
      return await this.service.deleteTalent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Employee, {
    nullable: true,
    name: "employee",
  })
  @nestAccessControl.UseRoles({
    resource: "Employee",
    action: "read",
    possession: "any",
  })
  async getEmployee(
    @graphql.Parent() parent: Talent
  ): Promise<Employee | null> {
    const result = await this.service.getEmployee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
