/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Workforce } from "./Workforce";
import { WorkforceCountArgs } from "./WorkforceCountArgs";
import { WorkforceFindManyArgs } from "./WorkforceFindManyArgs";
import { WorkforceFindUniqueArgs } from "./WorkforceFindUniqueArgs";
import { CreateWorkforceArgs } from "./CreateWorkforceArgs";
import { UpdateWorkforceArgs } from "./UpdateWorkforceArgs";
import { DeleteWorkforceArgs } from "./DeleteWorkforceArgs";
import { Employee } from "../../employee/base/Employee";
import { WorkforceService } from "../workforce.service";
@graphql.Resolver(() => Workforce)
export class WorkforceResolverBase {
  constructor(protected readonly service: WorkforceService) {}

  async _workforcesMeta(
    @graphql.Args() args: WorkforceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Workforce])
  async workforces(
    @graphql.Args() args: WorkforceFindManyArgs
  ): Promise<Workforce[]> {
    return this.service.workforces(args);
  }

  @graphql.Query(() => Workforce, { nullable: true })
  async workforce(
    @graphql.Args() args: WorkforceFindUniqueArgs
  ): Promise<Workforce | null> {
    const result = await this.service.workforce(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Workforce)
  async createWorkforce(
    @graphql.Args() args: CreateWorkforceArgs
  ): Promise<Workforce> {
    return await this.service.createWorkforce({
      ...args,
      data: {
        ...args.data,

        employee: args.data.employee
          ? {
              connect: args.data.employee,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Workforce)
  async updateWorkforce(
    @graphql.Args() args: UpdateWorkforceArgs
  ): Promise<Workforce | null> {
    try {
      return await this.service.updateWorkforce({
        ...args,
        data: {
          ...args.data,

          employee: args.data.employee
            ? {
                connect: args.data.employee,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Workforce)
  async deleteWorkforce(
    @graphql.Args() args: DeleteWorkforceArgs
  ): Promise<Workforce | null> {
    try {
      return await this.service.deleteWorkforce(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Employee, {
    nullable: true,
    name: "employee",
  })
  async getEmployee(
    @graphql.Parent() parent: Workforce
  ): Promise<Employee | null> {
    const result = await this.service.getEmployee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
