/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkforceService } from "../workforce.service";
import { WorkforceCreateInput } from "./WorkforceCreateInput";
import { Workforce } from "./Workforce";
import { WorkforceFindManyArgs } from "./WorkforceFindManyArgs";
import { WorkforceWhereUniqueInput } from "./WorkforceWhereUniqueInput";
import { WorkforceUpdateInput } from "./WorkforceUpdateInput";

export class WorkforceControllerBase {
  constructor(protected readonly service: WorkforceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Workforce })
  async createWorkforce(
    @common.Body() data: WorkforceCreateInput
  ): Promise<Workforce> {
    return await this.service.createWorkforce({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        budget: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        schedule: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Workforce] })
  @ApiNestedQuery(WorkforceFindManyArgs)
  async workforces(@common.Req() request: Request): Promise<Workforce[]> {
    const args = plainToClass(WorkforceFindManyArgs, request.query);
    return this.service.workforces({
      ...args,
      select: {
        budget: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        schedule: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Workforce })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async workforce(
    @common.Param() params: WorkforceWhereUniqueInput
  ): Promise<Workforce | null> {
    const result = await this.service.workforce({
      where: params,
      select: {
        budget: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        schedule: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Workforce })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWorkforce(
    @common.Param() params: WorkforceWhereUniqueInput,
    @common.Body() data: WorkforceUpdateInput
  ): Promise<Workforce | null> {
    try {
      return await this.service.updateWorkforce({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          budget: true,
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          schedule: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Workforce })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWorkforce(
    @common.Param() params: WorkforceWhereUniqueInput
  ): Promise<Workforce | null> {
    try {
      return await this.service.deleteWorkforce({
        where: params,
        select: {
          budget: true,
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          schedule: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
