/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PerformanceService } from "../performance.service";
import { PerformanceCreateInput } from "./PerformanceCreateInput";
import { Performance } from "./Performance";
import { PerformanceFindManyArgs } from "./PerformanceFindManyArgs";
import { PerformanceWhereUniqueInput } from "./PerformanceWhereUniqueInput";
import { PerformanceUpdateInput } from "./PerformanceUpdateInput";

export class PerformanceControllerBase {
  constructor(protected readonly service: PerformanceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Performance })
  async createPerformance(
    @common.Body() data: PerformanceCreateInput
  ): Promise<Performance> {
    return await this.service.createPerformance({
      data: {
        ...data,

        employee: data.employee
          ? {
              connect: data.employee,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        reviewDate: true,
        score: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Performance] })
  @ApiNestedQuery(PerformanceFindManyArgs)
  async performances(@common.Req() request: Request): Promise<Performance[]> {
    const args = plainToClass(PerformanceFindManyArgs, request.query);
    return this.service.performances({
      ...args,
      select: {
        comments: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        reviewDate: true,
        score: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async performance(
    @common.Param() params: PerformanceWhereUniqueInput
  ): Promise<Performance | null> {
    const result = await this.service.performance({
      where: params,
      select: {
        comments: true,
        createdAt: true,

        employee: {
          select: {
            id: true,
          },
        },

        id: true,
        reviewDate: true,
        score: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePerformance(
    @common.Param() params: PerformanceWhereUniqueInput,
    @common.Body() data: PerformanceUpdateInput
  ): Promise<Performance | null> {
    try {
      return await this.service.updatePerformance({
        where: params,
        data: {
          ...data,

          employee: data.employee
            ? {
                connect: data.employee,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          reviewDate: true,
          score: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Performance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePerformance(
    @common.Param() params: PerformanceWhereUniqueInput
  ): Promise<Performance | null> {
    try {
      return await this.service.deletePerformance({
        where: params,
        select: {
          comments: true,
          createdAt: true,

          employee: {
            select: {
              id: true,
            },
          },

          id: true,
          reviewDate: true,
          score: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
