/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ComplianceService } from "../compliance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ComplianceCreateInput } from "./ComplianceCreateInput";
import { Compliance } from "./Compliance";
import { ComplianceFindManyArgs } from "./ComplianceFindManyArgs";
import { ComplianceWhereUniqueInput } from "./ComplianceWhereUniqueInput";
import { ComplianceUpdateInput } from "./ComplianceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ComplianceControllerBase {
  constructor(
    protected readonly service: ComplianceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Compliance })
  @nestAccessControl.UseRoles({
    resource: "Compliance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ComplianceCreateInput,
  })
  async createCompliance(
    @common.Body() data: ComplianceCreateInput
  ): Promise<Compliance> {
    return await this.service.createCompliance({
      data: data,
      select: {
        complianceDate: true,
        createdAt: true,
        description: true,
        id: true,
        standardName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Compliance] })
  @ApiNestedQuery(ComplianceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Compliance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async compliances(@common.Req() request: Request): Promise<Compliance[]> {
    const args = plainToClass(ComplianceFindManyArgs, request.query);
    return this.service.compliances({
      ...args,
      select: {
        complianceDate: true,
        createdAt: true,
        description: true,
        id: true,
        standardName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Compliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compliance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async compliance(
    @common.Param() params: ComplianceWhereUniqueInput
  ): Promise<Compliance | null> {
    const result = await this.service.compliance({
      where: params,
      select: {
        complianceDate: true,
        createdAt: true,
        description: true,
        id: true,
        standardName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Compliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compliance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ComplianceUpdateInput,
  })
  async updateCompliance(
    @common.Param() params: ComplianceWhereUniqueInput,
    @common.Body() data: ComplianceUpdateInput
  ): Promise<Compliance | null> {
    try {
      return await this.service.updateCompliance({
        where: params,
        data: data,
        select: {
          complianceDate: true,
          createdAt: true,
          description: true,
          id: true,
          standardName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Compliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Compliance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCompliance(
    @common.Param() params: ComplianceWhereUniqueInput
  ): Promise<Compliance | null> {
    try {
      return await this.service.deleteCompliance({
        where: params,
        select: {
          complianceDate: true,
          createdAt: true,
          description: true,
          id: true,
          standardName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
