/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Benefit } from "./Benefit";
import { BenefitCountArgs } from "./BenefitCountArgs";
import { BenefitFindManyArgs } from "./BenefitFindManyArgs";
import { BenefitFindUniqueArgs } from "./BenefitFindUniqueArgs";
import { CreateBenefitArgs } from "./CreateBenefitArgs";
import { UpdateBenefitArgs } from "./UpdateBenefitArgs";
import { DeleteBenefitArgs } from "./DeleteBenefitArgs";
import { Employee } from "../../employee/base/Employee";
import { BenefitService } from "../benefit.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Benefit)
export class BenefitResolverBase {
  constructor(
    protected readonly service: BenefitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "any",
  })
  async _benefitsMeta(
    @graphql.Args() args: BenefitCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Benefit])
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "any",
  })
  async benefits(
    @graphql.Args() args: BenefitFindManyArgs
  ): Promise<Benefit[]> {
    return this.service.benefits(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Benefit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "own",
  })
  async benefit(
    @graphql.Args() args: BenefitFindUniqueArgs
  ): Promise<Benefit | null> {
    const result = await this.service.benefit(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "create",
    possession: "any",
  })
  async createBenefit(
    @graphql.Args() args: CreateBenefitArgs
  ): Promise<Benefit> {
    return await this.service.createBenefit({
      ...args,
      data: {
        ...args.data,

        employee: args.data.employee
          ? {
              connect: args.data.employee,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "update",
    possession: "any",
  })
  async updateBenefit(
    @graphql.Args() args: UpdateBenefitArgs
  ): Promise<Benefit | null> {
    try {
      return await this.service.updateBenefit({
        ...args,
        data: {
          ...args.data,

          employee: args.data.employee
            ? {
                connect: args.data.employee,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "delete",
    possession: "any",
  })
  async deleteBenefit(
    @graphql.Args() args: DeleteBenefitArgs
  ): Promise<Benefit | null> {
    try {
      return await this.service.deleteBenefit(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Employee, {
    nullable: true,
    name: "employee",
  })
  @nestAccessControl.UseRoles({
    resource: "Employee",
    action: "read",
    possession: "any",
  })
  async getEmployee(
    @graphql.Parent() parent: Benefit
  ): Promise<Employee | null> {
    const result = await this.service.getEmployee(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
